name: Continuous Integration

on: [push]

jobs:
  macos:
    name: macOS
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_13.2.app
    - name: Action
      run: make test

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - 5.5
        ubuntu:
          - bionic
          - focal
    steps:
    - uses: actions/checkout@v2
    - name: Action
      run: Scripts/ubuntu.sh test ${{ matrix.swift }} ${{ matrix.ubuntu }}
