name: Continuous Integration

on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macos-11
    strategy:
      matrix:
        action:
          - build
          - test
    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_13.2.app
    - name: Action
      run: make ${{ matrix.action }}

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - 5.5
        ubuntu:
          - bionic
          - focal
        action:
          - build
          - test
    steps:
    - uses: actions/checkout@v2
    - name: Action
      run: Scripts/ubuntu.sh ${{ matrix.action }} ${{ matrix.swift }} ${{ matrix.ubuntu }}
